#!/usr/bin/env node
// Turns generated/VadiumHook.abi.json (written by scripts/export-artifacts.mjs at
// the repo root) into generated/VadiumHook.abi.ts with an `as const` assertion, so
// Ponder and viem can infer event names and argument types.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const dir = join(dirname(fileURLToPath(import.meta.url)), "..", "generated");
const src = join(dir, "VadiumHook.abi.json");
const dst = join(dir, "VadiumHook.abi.ts");

if (!existsSync(src)) {
  console.error(`missing ${src}; run \`node scripts/export-artifacts.mjs\` from the repo root first`);
  process.exit(1);
}
const abi = JSON.parse(readFileSync(src, "utf8"));
writeFileSync(
  dst,
  `// Generated by scripts/abi.mjs from VadiumHook.abi.json. Do not edit.\nexport const VadiumHookAbi = ${JSON.stringify(abi, null, 2)} as const;\n`,
);
console.log(`wrote ${dst}`);
